language: objective-c

osx_image: xcode7.3
before_script: cd HelloWorld

notifications:
  email: false

script:
  - set -o pipefail &&
      xcodebuild
        CODE_SIGNING_REQUIRED=NO
        CODE_SIGN_IDENTITY=
        PROVISIONING_PROFILE=
        -sdk iphonesimulator
        -destination 'platform=iOS Simulator,OS=9.0,name=iPhone 6'
        -scheme "HelloWorld"
        clean build test |
        xcpretty
        
  - set -o pipefail &&
      xcodebuild
        CODE_SIGNING_REQUIRED=NO
        CODE_SIGN_IDENTITY=
        PROVISIONING_PROFILE=
        -sdk iphonesimulator
        -destination 'platform=iOS Simulator,OS=9.0,name=iPhone 6'
        -scheme "HelloWorld - Suite Two"
        clean build test |
      xcpretty

