language: objective-c

osx_image: xcode7.3
before_script: cd HelloWorld

notifications:
  email: false

before_install:
  - gem install xcov --no-ri --no-rdoc --no-document
  - gem install fastlane --no-ri --no-rdoc --no-document

script:
  - scripts/travis/script.sh
  - set -o pipefail &&
      xcodebuild
        CODE_SIGNING_REQUIRED=NO
        CODE_SIGN_IDENTITY=
        PROVISIONING_PROFILE=
        -sdk iphonesimulator
        -destination 'platform=iOS Simulator,OS=9.0,name=iPhone 6'
        -scheme "HelloWorld"
        clean build test |
        xcpretty -r "html" -o "tests.html"
        
  - set -o pipefail &&
      xcodebuild
        CODE_SIGNING_REQUIRED=NO
        CODE_SIGN_IDENTITY=
        PROVISIONING_PROFILE=
        -sdk iphonesimulator
        -destination 'platform=iOS Simulator,OS=9.0,name=iPhone 6'
        -scheme "HelloWorld - Suite Two"
        clean build test |
        xcpretty -r "html" -o "tests.html"

after_success:
  - scripts/travis/after_success_script.sh

